feat(): Release 2.4. - Payment widget
DUNA-E-Commmerce/deuna-sdk-android pull request #57
Opened 2024-07-15 18:38 UTC by darwinmorocho-deuna

This release contains the next major features:
- Added support for the payment link.
- Replaces CheckoutResponse and ElementsResponse by a Map<String,Any>.
- Updated the example apps.
- Added support for the userToken query parameter.

TICKETS:
https://deuna.atlassian.net/browse/PLAT-3506
https://deuna.atlassian.net/browse/PLAT-3480

2024-07-15 23:24 UTC, DinaRocio requested changes

2024-07-15 23:24 UTC, DinaRocio commented on examples/basic-integration-jetpack-compose/app/src/main/java/com/deuna/compose_demo/view_models/HomeViewModel.kt
> +val ERROR_TAG = "❌ DeunaSDK"
aqui no seria mejor utilizar const val ya que de ese modo se evalua en tiempo de compilacion

2024-07-15 23:24 UTC, DinaRocio commented on examples/basic-integration-jetpack-compose/app/src/main/java/com/deuna/compose_demo/view_models/HomeViewModel.kt
> +            onSuccess = { data ->
qué pasa aqui si sacas las funciones afuera de modo que luego puedan ser llamadas tipo:
        onSuccess = onCheckoutSuccess(completion)
        onError = onCheckoutError(completion)
        onCanceled = onCheckoutCanceled(completion)
        eventListener = onCheckoutEventListener()

2024-07-15 23:24 UTC, DinaRocio commented on examples/basic-integration-jetpack-compose/app/src/main/java/com/deuna/compose_demo/view_models/HomeViewModel.kt
> +            onSuccess = { data ->
tal vez podria ser mas conciso

2024-07-15 23:24 UTC, DinaRocio commented on examples/basic-integration-jetpack-compose/app/src/main/java/com/deuna/compose_demo/MainActivity.kt
> +                        PaymentSuccessfulScreen(
que pasa aqui si este json viene como null, manejamos esos casos?

2024-07-16 10:22 UTC, darwinmorocho-deuna commented on examples/basic-integration-jetpack-compose/app/src/main/java/com/deuna/compose_demo/MainActivity.kt
> +                        PaymentSuccessfulScreen(
No es necesario ya que es solo un demo en el cual se navega a dicha screen únicamente si el pago es exitoso y siempre se le pasa la data como JSON.

2024-07-16 10:26 UTC, darwinmorocho-deuna commented on examples/basic-integration-jetpack-compose/app/src/main/java/com/deuna/compose_demo/view_models/HomeViewModel.kt
> +            onSuccess = { data ->
en este caso no lo veo necesario ya que cada callback no contiene mucho codigo. Personalmente considero que moverlo a funciones no aportaria una mejor legibilidad para estos casos donde el codigo de cada callback es de pocas lineas.

```Kotlin
    private fun paymentWidgetsCallbacks(
        completion: (PaymentWidgetResult) -> Unit,
    ): PaymentWidgetCallbacks {
        return PaymentWidgetCallbacks().apply {
            onSuccess = { data ->
                deunaSDK.closePaymentWidget()
                viewModelScope.launch {
                    completion(
                        PaymentWidgetResult.Success(
                            data["order"] as Json
                        )
                    )
                }
            }
            onCanceled = {
                viewModelScope.launch {
                    completion(PaymentWidgetResult.Canceled)
                }
            }
            onError = { error ->
                Log.e(ERROR_TAG, "on error ${error.type} , ${error.metadata}")
                when (error.type) {
                    PaymentsError.Type.PAYMENT_ERROR,
                    PaymentsError.Type.NO_INTERNET_CONNECTION -> {
                        deunaSDK.closePaymentWidget()
                        completion(PaymentWidgetResult.Error(error))
                    }

                    else -> {}
                }

            }
            onClosed = {

            }
        }
    }
    ```

2024-07-16 17:47 UTC, DinaRocio approved these changes

2024-07-16 18:37 UTC, merged