feat(ENTP1-12112): Release 2.8.9 - Clic Air
DUNA-E-Commmerce/deuna-sdk-android pull request #72
Opened 2024-10-23 18:11 UTC by darwinmorocho-deuna

[TICKET](https://deuna.atlassian.net/browse/ENTP1-12112)

Improve the window.open handler to prevent conflicts with the original link.
Use native method to take a snapshot of the web view.
Added Support for clic Air.
DEMO SDK:

https://github.com/user-attachments/assets/b6b69d2b-93a9-4f06-ae70-0e065ed23373

2024-10-23 18:22 UTC, capdilla approved these changes

2024-10-23 18:29 UTC, HexerMelvin117 approved these changes

2024-10-23 18:36 UTC, devedux commented on src/main/java/com/deuna/maven/web_views/DeunaWebViewActivity.kt
> +         window.xprops = {
Estaria bien modificar el window.xprops?, creo que este contiene datos extras
cc @capdilla @darwinmorocho-deuna

2024-10-23 18:42 UTC, capdilla requested changes

2024-10-23 18:42 UTC, capdilla commented on src/main/java/com/deuna/maven/web_views/DeunaWebViewActivity.kt
> +         window.xprops = {
en mobile si, esta bien ya que no se injecta el xprops de zoid, sino que es un mock de eso para que funcione

2024-10-24 22:10 UTC, capdilla approved these changes

2024-10-25 00:43 UTC, merged